[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[cron.content_update]
schedule = "0 16 * * *"
command = "poetry run awesome_updater"

[cron.news_posting]
schedule = "0 1 * * *"
command = "poetry run python tools/src/post_news.py"