github:
  search:
    max_repos: 10
    query_terms:
      - awesome
      - embodied
      - ai
      - robotics
    sort: stars

content:
  sections:
    - projects
    - papers
    - datasets
    - companies

git:
  branch_prefix: update
  commit_message: "Update awesome list with new resources"

openai:
  model: "gpt-4"
  temperature: 0.3
  max_tokens: 1000
